### PR TITLE
Supports last-modified response header

### PR DESCRIPTION
**Pull request by kkazuo**
Added "metadata" feature.
If feature flag “metadata” enabled, includes Last-Modified response header and can conditional response with If-Modified-Since.

### CODE REVIEW

**Comment by jannik4** [comment]
Looks good, maybe you could add a little note about the new "metadata" feature in the Readme and lib.rs?
(Something like [this](https://docs.rs/include_dir/latest/include_dir/#features), for example)

**Comment by jannik4** [comment]
And maybe remove the asserts with the `etag` header. They confused me for a moment, since the `etag` header never gets added.

**Comment by kkazuo** [comment]
@jannik4 Thank you for taking your time.
I have fixed.
I appreciate the review again.

**Comment by jannik4** [comment]
Thanks, merging!

**Comment by jannik4** [comment]
And released in `0.1.1`.

**Pull request merged**
