### PR TITLE
fix is_dir() to return true for empty path

### PR DESCRIPTION
**Pull request by astraw**

### CODE REVIEW

**Comment by astraw** [comment]
This was likely inspired by the same issue as https://github.com/jannik4/tower-serve-static/pull/1. I'm not sure why that was closed.

**Comment by jannik4** [comment]
Thanks. Added a test, that failed without the fix.

**Comment by jannik4** [comment]
Hm, thats a strange error.

**Comment by astraw** [comment]
I think it is failing because the CI is testing the merge and the main branch already has #2 on it which changes `Body`.

**Comment by jannik4** [comment]
Thanks, rebased.

**Pull request merged**
